app:
    resource: "@AppBundle/Controller/"
    type:     annotation

prueba:
    path: /prueba
    defaults: { _controller: AppBundle:Prueba:index }

inscripcion:
    path: /inscripcion
    defaults: { _controller: AppBundle:Asistente:singUp }
asistentes:
    path: /asistentes
    defaults: { _controller:AppBundle:Asistente:showPublic }
colaborador_add:
    path: /colaborador/add
    defaults: { _controller: AppBundle:Colaborador:add }
