app:
    resource: "@AppBundle/Controller/"
    type:     annotation

prueba:
    path: /prueba
    defaults: { _controller: AppBundle:Prueba:index }

inscripcion:
    path: /inscripcion
    defaults: { _controller: AppBundle:Asistente:singUp }
asistentes:
    path: /asistentes
    defaults: { _controller:AppBundle:Asistente:showPublic }

colaborador_add:
    path: /colaborador/add
    defaults: { _controller: AppBundle:Colaborador:add }

llegar:
    path: /como-llegar
    defaults: { _controller: AppBundle:Llegar:index }
llegar_add:
    path: /admin/como-llegar/add
    defaults: { _controller: AppBundle:Llegar:add }
llegar_edit:
    path: /admin/como-llegar/{keyword}/edit
    defaults: { _controller: AppBundle:Llegar:edit }
llegar_remove:
    path: /admin/como-llegar/{keyword}/delete
    defaults: { _controller: AppBundle:Llegar:delete }

login:
    path: /admin/login
    defaults: { _controller: AppBundle:Administrator:login }
logout:
    path: /admin/logout
    defaults: { _controller: AppBundle:Administrator:logout }