app:
    resource: "@AppBundle/Controller/"
    type:     annotation



inscripcion:
    path: /inscripcion
    defaults: { _controller: AppBundle:Asistente:singUp }
asistentes:
    path: /asistentes
    defaults: { _controller:AppBundle:Asistente:showPublic }
asistente_admin:
    path: /admin/asistentes
    defaults: { _controller:AppBundle:Asistente:adminShow }
asistente_download:
    path: /admin/asistentes/download
    defaults: { _controller:AppBundle:Asistente:download }


colaborador_add:
    path: /admin/colaborador/add
    defaults: { _controller: AppBundle:Colaborador:add }
colaborador_edit:
    path: /admin/colaborador/{keyword}/edit
    defaults: { _controller: AppBundle:Colaborador:edit }
colaborador_remove:
    path: /admin/colaborador/{keyword}/delete
    defaults: { _controller: AppBundle:Colaborador:delete }


saludo_rector:
    path: /saludo-rector
    defaults: { _controller: AppBundle:Default:saludoRector }
programa:
    path: /programa
    defaults: { _controller: AppBundle:Default:programa }

alojamiento:
    path: /alojamiento
    defaults: {_controller: AppBundle:Default:alojamientos }


comunicaciones:
    path: /comunicados
    defaults: { _controller: AppBundle:Comunicados:index }

lpod:
    path: /politica-de-privacidad
    defaults: { _controller: AppBundle:Ley:index }

contact:
 path: /contacto
 defaults: { _controller: AppBundle:Contacto:index }

login:
    path: /admin/login
    defaults: { _controller: AppBundle:Administrator:login }
logout:
    path: /admin/logout
    defaults: { _controller: AppBundle:Administrator:logout }